namespace: elasticsearch
name: eda
version: 1.0.3
readme: README.md
authors:
  - Christian Mueller
  - Patrick Hermann
  - Colin McNaughton <@cloin>
description: Event-Driven Ansible content
license_file: 'LICENSE'
tags:
  - eda
  - elasticsearch
  - infrastructure
dependencies: {}
repository: https://github.com/stuttgart-things/elasticsearch.eda
documentation: https://github.com/stuttgart-things/elasticsearch.eda/tree/main/docs
issues: https://github.com/stuttgart-things/elasticsearch.eda/issues
build_ignore: []
